apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpdingress
spec:
  rules:
    - host: 44.201.27.92
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpd-deployment
                port:
                  number: 8080
